# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dfs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dfs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdfs.proto\x12\x03\x64\x66s\"*\n\x05\x43hunk\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"0\n\x0cUploadStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t2m\n\x08\x44\x61taNode\x12/\n\nUploadFile\x12\n.dfs.Chunk\x1a\x11.dfs.UploadStatus\"\x00(\x01\x12\x30\n\x0c\x44ownloadFile\x12\x10.dfs.FileRequest\x1a\n.dfs.Chunk\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNK']._serialized_start=18
  _globals['_CHUNK']._serialized_end=60
  _globals['_UPLOADSTATUS']._serialized_start=62
  _globals['_UPLOADSTATUS']._serialized_end=110
  _globals['_FILEREQUEST']._serialized_start=112
  _globals['_FILEREQUEST']._serialized_end=143
  _globals['_DATANODE']._serialized_start=145
  _globals['_DATANODE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
